F/profile photo
stemwana-youthdev/Explorer-Trail-2020 pull request #143
Opened 2020-08-18 21:46 UTC by Benjamin-Davies

Depends on #118 and #140

2020-08-28 06:00 UTC, kellymarjorie requested changes

2020-08-28 06:00 UTC, kellymarjorie commented on stem-explorer-ng/src/app/app.module.ts
> +import { HintDialogComponent } from './containers/hint-dialog/hint-dialog.component';
Have you merged the latest from develop? As this is no longer import into the app.module.ts

2020-08-28 06:00 UTC, kellymarjorie commented on stem-explorer-ng/src/app/containers/profile/profile.component.ts
> +    this.photoURLSubscription = this.auth.photoURL.subscribe((url) => {
What's your reasoning on storing the avatar in firebase instead of with the profile info?

2020-08-28 06:00 UTC, kellymarjorie commented on stem-explorer-ng/src/app/shared/auth/auth.service.ts
> +        console.log(user);
I think you forgot to remove this :)

2020-09-02 22:06 UTC, Benjamin-Davies commented on stem-explorer-ng/src/app/containers/profile/profile.component.ts
> +    this.photoURLSubscription = this.auth.photoURL.subscribe((url) => {
The profile backend wasn't implemented yet, and it avoided another request to the API server. The down-sides are that the profile picture is per-user, not per profile. I also had to compress the images more than I would like to keep under the size limit.

2020-09-03 06:11 UTC, merged