Show levels for challenge on list cards and challenge dialog
stemwana-youthdev/Explorer-Trail-2020 pull request #157
Opened 2020-08-26 02:49 UTC by Benjamin-Davies

2020-08-29 03:23 UTC, kellymarjorie requested changes

2020-08-29 03:23 UTC, kellymarjorie commented on StemExplorerAPI/StemExplorerAPI/Services/LocationService.cs
> +                                Complete = false,
Do we need the ID and the difficulty?

2020-08-29 03:23 UTC, kellymarjorie commented on StemExplorerAPI/StemExplorerAPI/Services/LocationService.cs
> +                }
We really shouldn't be doing 3 nested loops here. Is there a way we can do this better?

2020-08-29 03:23 UTC, kellymarjorie commented on stem-explorer-ng/src/app/store/progress/progress.state.ts
> +      tap((progress) => ctx.patchState({ progress, fetched: true }))
If progress is just going to be a property on the Challenge or Challenge Level object, do we need to have a store for it?

2020-08-29 03:23 UTC, kellymarjorie commented on stem-explorer-ng/src/app/store/profiles/profiles.state.ts
> +      switchMap(() => from(this.authService.getProfiles())),
How come we need to load all profiles to get the user's profile, or is this for all of the profiles for the logged in user?

2020-09-01 02:41 UTC, Benjamin-Davies commented on StemExplorerAPI/StemExplorerAPI/Services/LocationService.cs
> +                                Complete = false,
`Difficulty` is the number that is shown in the circle. For example, "Biscuits" does not have a level 1, so it wouldn't make sense to show a 1.

No, we don't need `ID`.

2020-09-01 03:11 UTC, Benjamin-Davies commented on StemExplorerAPI/StemExplorerAPI/Services/LocationService.cs
> +                                Complete = false,
Actually we need ID on to fill in the progress, but not on the client

2020-09-01 21:02 UTC, Benjamin-Davies commented on StemExplorerAPI/StemExplorerAPI/Services/LocationService.cs
> +                }
I don't think so. There are three nested loops because there are three nested lists.

2020-09-01 21:04 UTC, Benjamin-Davies commented on stem-explorer-ng/src/app/store/profiles/profiles.state.ts
> +      switchMap(() => from(this.authService.getProfiles())),
This method only loads the profiles for the current user.

2020-09-02 05:32 UTC, Benjamin-Davies commented on stem-explorer-ng/src/app/store/progress/progress.state.ts
> +      tap((progress) => ctx.patchState({ progress, fetched: true }))
Store removed and progress for challenge-view fixed

2020-09-05 06:35 UTC, kellymarjorie approved these changes

2020-09-05 06:35 UTC, merged