D/add box shadow for buttons
stemwana-youthdev/Explorer-Trail-2020 pull request #172
Opened 2020-08-30 04:47 UTC by jhc19

- added box shadows to the buttons and level selector.
- the margin of the marker-info box is adjusted to be able to render the box-shadow properly.
- reverted the values of the button outline border back to its original value.

2020-08-30 20:56 UTC, kellymarjorie requested changes

2020-08-30 20:56 UTC, kellymarjorie commented on stem-explorer-ng/src/styles.scss
> -  margin-top: 0;
Can you add this as a separate class for the H3 it's needed on? as now this margin is on every H3 we have (and we use it a lot :) ) and can you define it as 5px or which one it needs to be?

2020-08-31 22:45 UTC, jhc19 commented on stem-explorer-ng/src/styles.scss
> -  margin-top: 0;
Hi Kelly,

I've sorted that just moments ago. 👍

2020-09-01 05:20 UTC, kellymarjorie requested changes

2020-09-01 05:20 UTC, kellymarjorie commented on stem-explorer-ng/src/app/shared/components/challenge-title/challenge-title.component.scss
> +    margin-top: 15px; /*In order to fix the spacing between the level selector and h3 in challenge view*/
This `margin-top` needs to be added to a class unique to that element, as this is giving all titles that use this mixin that space at the top (in challenge dialog, list view, etc.)

2020-09-03 04:42 UTC, jhc19 commented on stem-explorer-ng/src/app/shared/components/challenge-title/challenge-title.component.scss
> +    margin-top: 15px; /*In order to fix the spacing between the level selector and h3 in challenge view*/
Hi Kelly,

I've made some changes, but I wasn't sure if it still causes the same issue and if it is written right.

2020-09-06 03:29 UTC, kellymarjorie approved these changes

2020-09-06 03:29 UTC, merged