F/filter design
stemwana-youthdev/Explorer-Trail-2020 pull request #193
Opened 2020-09-09 04:26 UTC by Benjamin-Davies

2020-09-09 06:20 UTC, kellymarjorie requested changes

2020-09-09 06:20 UTC, kellymarjorie commented on stem-explorer-ng/src/locations/components/challenge-filter/challenge-filter.component.html
> +    <img src="/assets/icons/FILTER-filter.svg" alt="Filter icon">
I should've picked this up in the last PR, but if we use the mat-icon svgIcon property to show these then they don't need to be recalled every time - if you go to your network tab on this branch now, you'll see switching between the list and map view that it's reloading the images each time. If we use the svgIcon, register them in the `app.component.ts` function `registerIcons` (and add them to the `icons.constants.ts` for type checking), then it only loads the files once.

2020-09-10 02:54 UTC, Benjamin-Davies commented on stem-explorer-ng/src/locations/components/challenge-filter/challenge-filter.component.html
> +    <img src="/assets/icons/FILTER-filter.svg" alt="Filter icon">
Thank you for pointing this out. I didn't realize that we were using custom mat-icons

2020-09-10 03:22 UTC, kellymarjorie approved these changes

2020-09-10 03:22 UTC, merged