F/profile reminder
stemwana-youthdev/Explorer-Trail-2020 pull request #201
Opened 2020-09-11 04:33 UTC by Benjamin-Davies

2020-09-13 06:43 UTC, kellymarjorie commented on stem-explorer-ng/src/app/core/auth/auth.service.ts
> +    this.profileReminder.remindUser();
I don't think we should be reminding the user to fill out their profile when they sign out?

2020-09-13 06:48 UTC, kellymarjorie requested changes

2020-09-13 06:48 UTC, kellymarjorie commented on stem-explorer-ng/src/app/core/auth/auth.service.ts
> +            this.profileReminder.remindUser();
I don't think we are meant to be pushing user's to the profile page when they first sign up but we could add a snackbar here to let them know they can fill out their profile

2020-09-14 00:02 UTC, Benjamin-Davies commented on stem-explorer-ng/src/app/core/auth/auth.service.ts
> +            this.profileReminder.remindUser();
https://trello.com/c/V0kbMYsp

2020-09-14 06:31 UTC, kellymarjorie approved these changes

2020-09-14 06:31 UTC, merged